In [1]:
%matplotlib inline
import itertools
import pandas as pd
import numpy as np
import sklearn.ensemble
from sklearn import metrics
#importing RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.feature_selection import chi2 
from sklearn.feature_selection import SelectFromModel 
from sklearn.feature_selection import SelectKBest
from sklearn import svm
#get_ipython().magic('matplotlib inline')
import matplotlib.pyplot as plt

In [2]:
raw_file = pd.read_csv('C://Users//bhuiy//Desktop//no_NAs_A.raw', sep=" ",nrows=268)
raw_file.head(3)

FID      IID  PAT  MAT  SEX  PHENOTYPE  rs12565286_C  rs12082473_A  \
0  NA06984  NA06984    0    0    0         -9             0             0   
1  NA06985  NA06985    0    0    0         -9             0             0   
2  NA06986  NA06986    0    0    0         -9             0             0   

   rs3094315_G  rs2286139_T      ...       rs5770820_A  rs9628187_T  \
0            0            2      ...                 0            0   
1            0            2      ...                 1            0   
2            0            2      ...                 0            1   

   rs6010063_A  rs715586_T  rs8137951_A  rs3810648_G  rs3865766_C  \
0            2           0            0            0            2   
1            0           0            2            1            0   
2            1           0            1            0            2   

   rs2238837_C  rs34726907_T  rs28729663_A  
0            0             0             0  
1            1             1             1  
2            0             0             0  

[3 rows x 857130 columns]

In [4]:
raw_file.head(3)

FID      IID  PAT  MAT  SEX  PHENOTYPE  rs12565286_C  rs12082473_A  \
0  NA06984  NA06984    0    0    0         -9             0             0   
1  NA06985  NA06985    0    0    0         -9             0             0   
2  NA06986  NA06986    0    0    0         -9             0             0   

   rs3094315_G  rs2286139_T      ...       rs5770820_A  rs9628187_T  \
0            0            2      ...                 0            0   
1            0            2      ...                 1            0   
2            0            2      ...                 0            1   

   rs6010063_A  rs715586_T  rs8137951_A  rs3810648_G  rs3865766_C  \
0            2           0            0            0            2   
1            0           0            2            1            0   
2            1           0            1            0            2   

   rs2238837_C  rs34726907_T  rs28729663_A  
0            0             0             0  
1            1             1             1  
2            0             0             0  

[3 rows x 857130 columns]

In [3]:
raw_file=raw_file.drop(raw_file.columns[[0,1,2,3,4,5]],axis=1)
#print(raw_file.head(3))

In [4]:
snps=list(raw_file.columns.values)
len(snps)

857124

In [5]:
pops=pd.read_csv('C://Users//bhuiy//Desktop//pop_names', sep=" ",nrows=268)
pops=pops.drop('IID',axis=1)

In [12]:
y = np.array(pops['pop'])
#converting the covariates into a matrix
X_train, X_test, ytrain, ytest = train_test_split(raw_file,y,test_size=0.33)
X = raw_file.as_matrix(columns=None)

In [21]:
linear_svc.score(X_test,ytest)

0.9662921348314607

In [17]:
##support vector machine 
linear_svc= svm.SVC(kernel='linear',C=1).fit(X_train,ytrain)
rbf_svc = svm.SVC(kernel='rbf', gamma=0.7, C=1).fit(X_train, ytrain)

In [34]:
linear_svc.support_vectors_

array([[ 0.,  0.,  1., ...,  1.,  0.,  0.],
       [ 0.,  1.,  2., ...,  1.,  1.,  1.],
       [ 0.,  1.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  2., ...,  1.,  1.,  0.],
       [ 0.,  0.,  2., ...,  1.,  1.,  1.],
       [ 0.,  0.,  1., ...,  2.,  2.,  1.]])

In [35]:
weights = np.array(linear_svc.coef_)
weights

array([[  1.06038996e-06,   3.97082218e-06,   9.40335169e-06, ...,
          3.29136032e-06,  -5.91091361e-06,  -1.08079026e-06],
       [  8.42969012e-06,  -1.07030166e-05,  -2.01917056e-05, ...,
         -7.34713942e-06,  -2.90160638e-07,   1.23292473e-05],
       [  8.17787313e-07,  -4.68032562e-06,  -1.07002080e-05, ...,
         -3.64552736e-06,  -4.47361565e-06,  -1.80207585e-06]])

In [37]:
weights_model0 = np.array(weights[0])
weights_model1 = np.array(weights[1])
weights_model2 = np.array(weights[2])
weights_model0 = np.abs(weights_model0)
weights_model1 = np.abs(weights_model1)
weights_model2 = np.abs(weights_model2)

In [39]:
weights_model0

array([  1.06038996e-06,   3.97082218e-06,   9.40335169e-06, ...,
         3.29136032e-06,   5.91091361e-06,   1.08079026e-06])

In [40]:
weights_model1 


array([  8.42969012e-06,   1.07030166e-05,   2.01917056e-05, ...,
         7.34713942e-06,   2.90160638e-07,   1.23292473e-05])

In [41]:
weights_model2 

array([  8.17787313e-07,   4.68032562e-06,   1.07002080e-05, ...,
         3.64552736e-06,   4.47361565e-06,   1.80207585e-06])

In [97]:
y_pred = classifier.fit(X_train, ytrain).predict(X_test)
print(y_pred)

['YRI' 'YRI' 'CEU' 'YRI' 'CEU' 'ASW' 'YRI' 'CEU' 'ASW' 'CEU' 'CEU' 'YRI'
 'CEU' 'YRI' 'YRI' 'YRI' 'YRI' 'CEU' 'YRI' 'YRI' 'YRI' 'YRI' 'CEU' 'YRI'
 'YRI' 'YRI' 'YRI' 'YRI' 'CEU' 'ASW' 'YRI' 'YRI' 'YRI' 'YRI' 'YRI' 'CEU'
 'YRI' 'YRI' 'CEU' 'CEU' 'YRI' 'YRI' 'YRI' 'CEU' 'YRI' 'ASW' 'YRI' 'YRI'
 'ASW' 'ASW' 'ASW' 'YRI' 'YRI' 'ASW' 'YRI' 'YRI' 'YRI' 'ASW' 'ASW' 'ASW'
 'YRI' 'YRI' 'ASW' 'CEU' 'CEU' 'CEU' 'CEU' 'CEU' 'CEU' 'YRI' 'CEU' 'ASW'
 'CEU' 'CEU' 'YRI' 'CEU' 'YRI' 'CEU' 'YRI' 'CEU' 'ASW' 'YRI' 'YRI' 'CEU'
 'ASW' 'YRI' 'ASW' 'YRI' 'YRI']


In [106]:
#mean accuracy 
print (linear_svc.score(X,y))
# Compute confusion matrix
cnf_matrix = confusion_matrix(ytest, y_pred)
print (cnf_matrix)

0.988805970149
[[16  0  3]
 [ 0 26  0]
 [ 0  0 44]]


In [95]:
print(metrics.classification_report(ytest, y_pred))


             precision    recall  f1-score   support

        ASW       1.00      0.84      0.91        19
        CEU       1.00      1.00      1.00        26
        YRI       0.94      1.00      0.97        44

avg / total       0.97      0.97      0.97        89



In [125]:
model=SelectFromModel(linear_svc,prefit=True)
new_X=model.transform(X) 